spring:
  application:
    name: dragons_api
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  profiles:
    default: local
  config:
    import:
      - feign.yml
      - jpa.yml
      - logging.yml
